# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.asset_families_embedded_items_inner_all_of_product_link_rules_inner_assign_assets_to_inner import AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner  # noqa: E501
from openapi_client.rest import ApiException

class TestAssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner(unittest.TestCase):
    """AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner`
        """
        model = openapi_client.models.asset_families_embedded_items_inner_all_of_product_link_rules_inner_assign_assets_to_inner.AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner()  # noqa: E501
        if include_optional :
            return AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner(
                attribute = '', 
                locale = '', 
                channel = '', 
                mode = ''
            )
        else :
            return AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner(
                attribute = '',
                mode = '',
        )
        """

    def testAssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner(self):
        """Test AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerAssignAssetsToInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
