# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.deprecated_asset_list_all_of_variation_files import DeprecatedAssetListAllOfVariationFiles  # noqa: E501
from openapi_client.rest import ApiException

class TestDeprecatedAssetListAllOfVariationFiles(unittest.TestCase):
    """DeprecatedAssetListAllOfVariationFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DeprecatedAssetListAllOfVariationFiles
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeprecatedAssetListAllOfVariationFiles`
        """
        model = openapi_client.models.deprecated_asset_list_all_of_variation_files.DeprecatedAssetListAllOfVariationFiles()  # noqa: E501
        if include_optional :
            return DeprecatedAssetListAllOfVariationFiles(
                link = openapi_client.models.deprecated_asset_list_all_of__link.DeprecatedAssetList_allOf__link(
                    self = openapi_client.models.deprecated_asset_list_all_of__link_self.DeprecatedAssetList_allOf__link_self(
                        href = '', ), 
                    download = openapi_client.models.deprecated_asset_list_all_of__link_download.DeprecatedAssetList_allOf__link_download(
                        href = '', ), ), 
                locale = '', 
                scope = '', 
                code = ''
            )
        else :
            return DeprecatedAssetListAllOfVariationFiles(
        )
        """

    def testDeprecatedAssetListAllOfVariationFiles(self):
        """Test DeprecatedAssetListAllOfVariationFiles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
