# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.pam_asset_category_api import PAMAssetCategoryApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPAMAssetCategoryApi(unittest.TestCase):
    """PAMAssetCategoryApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.pam_asset_category_api.PAMAssetCategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_asset_categories(self):
        """Test case for get_asset_categories

        Get list of PAM asset categories  # noqa: E501
        """
        pass

    def test_get_asset_categories_code(self):
        """Test case for get_asset_categories_code

        Get a PAM asset category  # noqa: E501
        """
        pass

    def test_patch_asset_categories(self):
        """Test case for patch_asset_categories

        Update/create several PAM asset categories  # noqa: E501
        """
        pass

    def test_patch_asset_categories_code(self):
        """Test case for patch_asset_categories_code

        Update/create a PAM asset category  # noqa: E501
        """
        pass

    def test_post_asset_categories(self):
        """Test case for post_asset_categories

        Create a new PAM asset category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
