# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.get_asset_family_code200_response import GetAssetFamilyCode200Response  # noqa: E501
from openapi_client.rest import ApiException

class TestGetAssetFamilyCode200Response(unittest.TestCase):
    """GetAssetFamilyCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAssetFamilyCode200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetFamilyCode200Response`
        """
        model = openapi_client.models.get_asset_family_code200_response.GetAssetFamilyCode200Response()  # noqa: E501
        if include_optional :
            return GetAssetFamilyCode200Response(
                code = '', 
                labels = openapi_client.models.get_asset_family__code__200_response_labels.get_asset_family__code__200_response_labels(
                    locale_code = '', ), 
                attribute_as_main_media = 'First media file or media link attribute that was created', 
                naming_convention = openapi_client.models.get_asset_family__code__200_response_naming_convention.get_asset_family__code__200_response_naming_convention(
                    source = openapi_client.models.source.source(), 
                    pattern = '', 
                    abort_asset_creation_on_error = True, ), 
                product_link_rules = [
                    openapi_client.models.get_asset_family__code__200_response_product_link_rules_inner.get_asset_family__code__200_response_product_link_rules_inner(
                        product_selections = [
                            openapi_client.models.get_asset_family__code__200_response_product_link_rules_inner_product_selections_inner.get_asset_family__code__200_response_product_link_rules_inner_product_selections_inner(
                                field = '', 
                                operator = '', 
                                value = '', 
                                locale = '', 
                                channel = '', )
                            ], 
                        assign_assets_to = [
                            openapi_client.models.get_asset_family__code__200_response_product_link_rules_inner_assign_assets_to_inner.get_asset_family__code__200_response_product_link_rules_inner_assign_assets_to_inner(
                                attribute = '', 
                                locale = '', 
                                channel = '', 
                                mode = '', )
                            ], )
                    ], 
                transformations = [
                    openapi_client.models.get_asset_family__code__200_response_transformations_inner.get_asset_family__code__200_response_transformations_inner(
                        label = '', 
                        filename_suffix = '', 
                        filename_prefix = '', 
                        source = openapi_client.models.get_asset_family__code__200_response_transformations_inner_source.get_asset_family__code__200_response_transformations_inner_source(
                            attribute = '', 
                            channel = '', 
                            locale = '', ), 
                        target = openapi_client.models.get_asset_family__code__200_response_transformations_inner_target.get_asset_family__code__200_response_transformations_inner_target(
                            attribute = '', 
                            channel = '', 
                            locale = '', ), 
                        operations = openapi_client.models.get_asset_family__code__200_response_transformations_inner_operations.get_asset_family__code__200_response_transformations_inner_operations(
                            type = '', 
                            parameters = openapi_client.models.get_asset_family__code__200_response_transformations_inner_operations_parameters.get_asset_family__code__200_response_transformations_inner_operations_parameters(
                                colorspace = '', 
                                width = 56, 
                                height = 56, 
                                ratio = 56, 
                                resolution_unit = '', 
                                resolution_x = 56, 
                                resolution_y = 56, 
                                quality = 56, ), ), )
                    ]
            )
        else :
            return GetAssetFamilyCode200Response(
                code = '',
        )
        """

    def testGetAssetFamilyCode200Response(self):
        """Test GetAssetFamilyCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
