# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_token200_response import PostToken200Response  # noqa: E501
from openapi_client.rest import ApiException

class TestPostToken200Response(unittest.TestCase):
    """PostToken200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostToken200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostToken200Response`
        """
        model = openapi_client.models.post_token200_response.PostToken200Response()  # noqa: E501
        if include_optional :
            return PostToken200Response(
                access_token = '', 
                expires_in = 56, 
                token_type = '', 
                scope = '', 
                refresh_token = ''
            )
        else :
            return PostToken200Response(
        )
        """

    def testPostToken200Response(self):
        """Test PostToken200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
