# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.pam_asset_api import PAMAssetApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPAMAssetApi(unittest.TestCase):
    """PAMAssetApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.pam_asset_api.PAMAssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_pam_assets(self):
        """Test case for get_pam_assets

        Get list of PAM assets  # noqa: E501
        """
        pass

    def test_get_pam_assets_code(self):
        """Test case for get_pam_assets_code

        Get a PAM asset  # noqa: E501
        """
        pass

    def test_patch_pam_assets(self):
        """Test case for patch_pam_assets

        Update/create several PAM assets  # noqa: E501
        """
        pass

    def test_patch_pam_assets_code(self):
        """Test case for patch_pam_assets_code

        Update/create a PAM asset  # noqa: E501
        """
        pass

    def test_post_pam_assets(self):
        """Test case for post_pam_assets

        Create a new PAM asset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
