# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.catalogs_api import CatalogsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCatalogsApi(unittest.TestCase):
    """CatalogsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.catalogs_api.CatalogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_app_catalog(self):
        """Test case for delete_app_catalog

        Delete a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalog(self):
        """Test case for get_app_catalog

        Get a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalogs(self):
        """Test case for get_app_catalogs

        Get the list of owned catalogs  # noqa: E501
        """
        pass

    def test_patch_app_catalog(self):
        """Test case for patch_app_catalog

        Update a catalog  # noqa: E501
        """
        pass

    def test_post_app_catalog(self):
        """Test case for post_app_catalog

        Create a new catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
