# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_attributes_attribute_code_options_request import PostAttributesAttributeCodeOptionsRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestPostAttributesAttributeCodeOptionsRequest(unittest.TestCase):
    """PostAttributesAttributeCodeOptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostAttributesAttributeCodeOptionsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAttributesAttributeCodeOptionsRequest`
        """
        model = openapi_client.models.post_attributes_attribute_code_options_request.PostAttributesAttributeCodeOptionsRequest()  # noqa: E501
        if include_optional :
            return PostAttributesAttributeCodeOptionsRequest(
                code = '', 
                attribute = '', 
                sort_order = 56, 
                labels = openapi_client.models.post_attributes__attribute_code__options_request_labels.post_attributes__attribute_code__options_request_labels(
                    locale_code = '', )
            )
        else :
            return PostAttributesAttributeCodeOptionsRequest(
                code = '',
        )
        """

    def testPostAttributesAttributeCodeOptionsRequest(self):
        """Test PostAttributesAttributeCodeOptionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
