# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.reference_entity_attribute_option_api import ReferenceEntityAttributeOptionApi  # noqa: E501
from openapi_client.rest import ApiException


class TestReferenceEntityAttributeOptionApi(unittest.TestCase):
    """ReferenceEntityAttributeOptionApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.reference_entity_attribute_option_api.ReferenceEntityAttributeOptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reference_entity_attributes_attribute_code_options(self):
        """Test case for get_reference_entity_attributes_attribute_code_options

        Get a list of attribute options of a given attribute for a given reference entity  # noqa: E501
        """
        pass

    def test_get_reference_entity_attributes_attribute_code_options_code(self):
        """Test case for get_reference_entity_attributes_attribute_code_options_code

        Get an attribute option for a given attribute of a given reference entity  # noqa: E501
        """
        pass

    def test_patch_reference_entity_attributes_attribute_code_options_code(self):
        """Test case for patch_reference_entity_attributes_attribute_code_options_code

        Update/create a reference entity attribute option  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
