# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.mapping_schema_for_products_api import MappingSchemaForProductsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMappingSchemaForProductsApi(unittest.TestCase):
    """MappingSchemaForProductsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.mapping_schema_for_products_api.MappingSchemaForProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_app_catalogs_mapping_schema_product(self):
        """Test case for delete_app_catalogs_mapping_schema_product

        Delete the product mapping schema related to a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalogs_mapping_schema_product(self):
        """Test case for get_app_catalogs_mapping_schema_product

        Get the product mapping schema related to a catalog  # noqa: E501
        """
        pass

    def test_put_app_catalogs_mapping_schema_product(self):
        """Test case for put_app_catalogs_mapping_schema_product

        Create or update the product mapping schema related to a catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
