# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.pam_asset_tag_api import PAMAssetTagApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPAMAssetTagApi(unittest.TestCase):
    """PAMAssetTagApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.pam_asset_tag_api.PAMAssetTagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_asset_tags(self):
        """Test case for get_asset_tags

        Get list of PAM asset tags  # noqa: E501
        """
        pass

    def test_get_asset_tags_code(self):
        """Test case for get_asset_tags_code

        Get a PAM asset tag  # noqa: E501
        """
        pass

    def test_patch_asset_tags_code(self):
        """Test case for patch_asset_tags_code

        Update/create a PAM asset tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
