# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.asset_family_list_all_of_transformations import AssetFamilyListAllOfTransformations  # noqa: E501
from openapi_client.rest import ApiException

class TestAssetFamilyListAllOfTransformations(unittest.TestCase):
    """AssetFamilyListAllOfTransformations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AssetFamilyListAllOfTransformations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetFamilyListAllOfTransformations`
        """
        model = openapi_client.models.asset_family_list_all_of_transformations.AssetFamilyListAllOfTransformations()  # noqa: E501
        if include_optional :
            return AssetFamilyListAllOfTransformations(
                label = '', 
                filename_suffix = '', 
                filename_prefix = '', 
                source = openapi_client.models.asset_family_list_all_of_source.AssetFamilyList_allOf_source(
                    attribute = '', 
                    channel = '', 
                    locale = '', ), 
                target = openapi_client.models.asset_family_list_all_of_target.AssetFamilyList_allOf_target(
                    attribute = '', 
                    channel = '', 
                    locale = '', ), 
                operations = openapi_client.models.asset_family_list_all_of_operations.AssetFamilyList_allOf_operations(
                    type = '', 
                    parameters = openapi_client.models.asset_family_list_all_of_operations_parameters.AssetFamilyList_allOf_operations_parameters(
                        colorspace = '', 
                        width = 56, 
                        height = 56, 
                        ratio = 56, 
                        resolution_unit = '', 
                        resolution_x = 56, 
                        resolution_y = 56, 
                        quality = 56, ), )
            )
        else :
            return AssetFamilyListAllOfTransformations(
                label = '',
                source = openapi_client.models.asset_family_list_all_of_source.AssetFamilyList_allOf_source(
                    attribute = '', 
                    channel = '', 
                    locale = '', ),
                target = openapi_client.models.asset_family_list_all_of_target.AssetFamilyList_allOf_target(
                    attribute = '', 
                    channel = '', 
                    locale = '', ),
                operations = openapi_client.models.asset_family_list_all_of_operations.AssetFamilyList_allOf_operations(
                    type = '', 
                    parameters = openapi_client.models.asset_family_list_all_of_operations_parameters.AssetFamilyList_allOf_operations_parameters(
                        colorspace = '', 
                        width = 56, 
                        height = 56, 
                        ratio = 56, 
                        resolution_unit = '', 
                        resolution_x = 56, 
                        resolution_y = 56, 
                        quality = 56, ), ),
        )
        """

    def testAssetFamilyListAllOfTransformations(self):
        """Test AssetFamilyListAllOfTransformations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
