# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.media_file_all_of1 import MediaFileAllOf1  # noqa: E501
from openapi_client.rest import ApiException

class TestMediaFileAllOf1(unittest.TestCase):
    """MediaFileAllOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MediaFileAllOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaFileAllOf1`
        """
        model = openapi_client.models.media_file_all_of1.MediaFileAllOf1()  # noqa: E501
        if include_optional :
            return MediaFileAllOf1(
                code = '', 
                original_filename = '', 
                mime_type = '', 
                size = 56, 
                extension = ''
            )
        else :
            return MediaFileAllOf1(
        )
        """

    def testMediaFileAllOf1(self):
        """Test MediaFileAllOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
