# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.channel_list_all_of_conversion_units import ChannelListAllOfConversionUnits  # noqa: E501
from openapi_client.rest import ApiException

class TestChannelListAllOfConversionUnits(unittest.TestCase):
    """ChannelListAllOfConversionUnits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ChannelListAllOfConversionUnits
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelListAllOfConversionUnits`
        """
        model = openapi_client.models.channel_list_all_of_conversion_units.ChannelListAllOfConversionUnits()  # noqa: E501
        if include_optional :
            return ChannelListAllOfConversionUnits(
                attribute_code = ''
            )
        else :
            return ChannelListAllOfConversionUnits(
        )
        """

    def testChannelListAllOfConversionUnits(self):
        """Test ChannelListAllOfConversionUnits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
