# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.pam_assets_embedded_items_inner_all_of import PAMAssetsEmbeddedItemsInnerAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestPAMAssetsEmbeddedItemsInnerAllOf(unittest.TestCase):
    """PAMAssetsEmbeddedItemsInnerAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PAMAssetsEmbeddedItemsInnerAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PAMAssetsEmbeddedItemsInnerAllOf`
        """
        model = openapi_client.models.pam_assets_embedded_items_inner_all_of.PAMAssetsEmbeddedItemsInnerAllOf()  # noqa: E501
        if include_optional :
            return PAMAssetsEmbeddedItemsInnerAllOf(
                code = '', 
                categories = [
                    ''
                    ], 
                description = '', 
                localizable = True, 
                tags = [
                    ''
                    ], 
                end_of_use = '', 
                variation_files = [
                    openapi_client.models.pam_assets__embedded_items_inner_all_of_variation_files_inner.PAM_Assets__embedded_items_inner_allOf_variation_files_inner(
                        _link = openapi_client.models.pam_assets__embedded_items_inner_all_of_variation_files_inner__link.PAM_Assets__embedded_items_inner_allOf_variation_files_inner__link(
                            self = openapi_client.models.pam_assets__embedded_items_inner_all_of_variation_files_inner__link_self.PAM_Assets__embedded_items_inner_allOf_variation_files_inner__link_self(
                                href = '', ), 
                            download = openapi_client.models.pam_assets__embedded_items_inner_all_of_variation_files_inner__link_download.PAM_Assets__embedded_items_inner_allOf_variation_files_inner__link_download(
                                href = '', ), ), 
                        locale = '', 
                        scope = '', 
                        code = '', )
                    ], 
                reference_files = [
                    openapi_client.models.pam_assets__embedded_items_inner_all_of_reference_files_inner.PAM_Assets__embedded_items_inner_allOf_reference_files_inner(
                        _link = openapi_client.models.pam_assets__embedded_items_inner_all_of_reference_files_inner__link.PAM_Assets__embedded_items_inner_allOf_reference_files_inner__link(
                            self = openapi_client.models.pam_assets__embedded_items_inner_all_of_reference_files_inner__link_self.PAM_Assets__embedded_items_inner_allOf_reference_files_inner__link_self(
                                href = '', ), 
                            download = openapi_client.models.pam_assets__embedded_items_inner_all_of_reference_files_inner__link_download.PAM_Assets__embedded_items_inner_allOf_reference_files_inner__link_download(
                                href = '', ), ), 
                        locale = '', 
                        code = '', )
                    ]
            )
        else :
            return PAMAssetsEmbeddedItemsInnerAllOf(
                code = '',
        )
        """

    def testPAMAssetsEmbeddedItemsInnerAllOf(self):
        """Test PAMAssetsEmbeddedItemsInnerAllOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
