# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.published_products_embedded_items_inner import PublishedProductsEmbeddedItemsInner  # noqa: E501
from openapi_client.rest import ApiException

class TestPublishedProductsEmbeddedItemsInner(unittest.TestCase):
    """PublishedProductsEmbeddedItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PublishedProductsEmbeddedItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishedProductsEmbeddedItemsInner`
        """
        model = openapi_client.models.published_products_embedded_items_inner.PublishedProductsEmbeddedItemsInner()  # noqa: E501
        if include_optional :
            return PublishedProductsEmbeddedItemsInner(
                links = openapi_client.models.products__embedded_items_inner_all_of__links.Products__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products__embedded_items_inner_all_of__links_self.Products__embedded_items_inner_allOf__links_self(
                        href = '', ), ), 
                identifier = '', 
                enabled = True, 
                family = '', 
                categories = [
                    ''
                    ], 
                groups = [
                    ''
                    ], 
                values = {
                    'key' : [
                        openapi_client.models.product_models__embedded_items_inner_all_of_values_value_inner.Product_Models__embedded_items_inner_allOf_values_value_inner(
                            scope = '', 
                            locale = '', 
                            data = openapi_client.models.data.data(), )
                        ]
                    }, 
                associations = openapi_client.models.published_products__embedded_items_inner_all_of_associations.Published_products__embedded_items_inner_allOf_associations(
                    association_type_code = openapi_client.models.published_products__embedded_items_inner_all_of_associations_association_type_code.Published_products__embedded_items_inner_allOf_associations_associationTypeCode(
                        groups = [
                            ''
                            ], 
                        products = [
                            ''
                            ], 
                        product_models = [
                            ''
                            ], ), ), 
                quantified_associations = None, 
                created = '', 
                updated = ''
            )
        else :
            return PublishedProductsEmbeddedItemsInner(
                identifier = '',
        )
        """

    def testPublishedProductsEmbeddedItemsInner(self):
        """Test PublishedProductsEmbeddedItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
