# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.family_api import FamilyApi  # noqa: E501
from openapi_client.rest import ApiException


class TestFamilyApi(unittest.TestCase):
    """FamilyApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.family_api.FamilyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_families(self):
        """Test case for get_families

        Get list of families  # noqa: E501
        """
        pass

    def test_get_families_code(self):
        """Test case for get_families_code

        Get a family  # noqa: E501
        """
        pass

    def test_patch_families(self):
        """Test case for patch_families

        Update/create several families  # noqa: E501
        """
        pass

    def test_patch_families_code(self):
        """Test case for patch_families_code

        Update/create a family  # noqa: E501
        """
        pass

    def test_post_families(self):
        """Test case for post_families

        Create a new family  # noqa: E501
        """
        pass

    def test_post_families_family_code_variants(self):
        """Test case for post_families_family_code_variants

        Create a new family variant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
