# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.measure_families_embedded_items_inner import MeasureFamiliesEmbeddedItemsInner  # noqa: E501
from openapi_client.rest import ApiException

class TestMeasureFamiliesEmbeddedItemsInner(unittest.TestCase):
    """MeasureFamiliesEmbeddedItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MeasureFamiliesEmbeddedItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeasureFamiliesEmbeddedItemsInner`
        """
        model = openapi_client.models.measure_families_embedded_items_inner.MeasureFamiliesEmbeddedItemsInner()  # noqa: E501
        if include_optional :
            return MeasureFamiliesEmbeddedItemsInner(
                links = openapi_client.models.products__embedded_items_inner_all_of__links.Products__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products__embedded_items_inner_all_of__links_self.Products__embedded_items_inner_allOf__links_self(
                        href = '', ), ), 
                code = '', 
                standard = '', 
                units = [
                    openapi_client.models.measure_families__embedded_items_inner_all_of_units_inner.Measure_Families__embedded_items_inner_allOf_units_inner(
                        code = '', 
                        convert = openapi_client.models.convert.convert(), 
                        symbol = '', )
                    ]
            )
        else :
            return MeasureFamiliesEmbeddedItemsInner(
                code = '',
        )
        """

    def testMeasureFamiliesEmbeddedItemsInner(self):
        """Test MeasureFamiliesEmbeddedItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
