# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.product_model_list_all_of_quantified_associations_quantified_association_type_code import ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode  # noqa: E501
from openapi_client.rest import ApiException

class TestProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode(unittest.TestCase):
    """ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode`
        """
        model = openapi_client.models.product_model_list_all_of_quantified_associations_quantified_association_type_code.ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode()  # noqa: E501
        if include_optional :
            return ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode(
                products = [
                    openapi_client.models.product_list_all_of_1_quantified_associations_quantified_association_type_code_products.ProductList_allOf_1_quantified_associations_quantifiedAssociationTypeCode_products(
                        identifier = '', 
                        quantity = 56, )
                    ], 
                product_models = [
                    openapi_client.models.product_list_all_of_1_quantified_associations_quantified_association_type_code_product_models.ProductList_allOf_1_quantified_associations_quantifiedAssociationTypeCode_product_models(
                        code = '', 
                        quantity = 56, )
                    ]
            )
        else :
            return ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode(
        )
        """

    def testProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode(self):
        """Test ProductModelListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
