# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.category_api import CategoryApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCategoryApi(unittest.TestCase):
    """CategoryApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.category_api.CategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_categories(self):
        """Test case for get_categories

        Get list of categories  # noqa: E501
        """
        pass

    def test_get_categories_code(self):
        """Test case for get_categories_code

        Get a category  # noqa: E501
        """
        pass

    def test_get_category_media_files_code_download(self):
        """Test case for get_category_media_files_code_download

        Download a category media file [COMING SOON]  # noqa: E501
        """
        pass

    def test_patch_categories(self):
        """Test case for patch_categories

        Update/create several categories  # noqa: E501
        """
        pass

    def test_patch_categories_code(self):
        """Test case for patch_categories_code

        Update/create a category  # noqa: E501
        """
        pass

    def test_post_categories(self):
        """Test case for post_categories

        Create a new category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
