# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.attribute_group_api import AttributeGroupApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAttributeGroupApi(unittest.TestCase):
    """AttributeGroupApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.attribute_group_api.AttributeGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attribute_groups_get(self):
        """Test case for attribute_groups_get

        Get an attribute group  # noqa: E501
        """
        pass

    def test_attribute_groups_get_list(self):
        """Test case for attribute_groups_get_list

        Get list of attribute groups  # noqa: E501
        """
        pass

    def test_attribute_groups_patch(self):
        """Test case for attribute_groups_patch

        Update/create an attribute group  # noqa: E501
        """
        pass

    def test_attribute_groups_post(self):
        """Test case for attribute_groups_post

        Create a new attribute group  # noqa: E501
        """
        pass

    def test_several_attribute_groups_patch(self):
        """Test case for several_attribute_groups_patch

        Update/create several attribute groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
