# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.get_asset_family_code200_response_product_link_rules_inner import GetAssetFamilyCode200ResponseProductLinkRulesInner  # noqa: E501
from openapi_client.rest import ApiException

class TestGetAssetFamilyCode200ResponseProductLinkRulesInner(unittest.TestCase):
    """GetAssetFamilyCode200ResponseProductLinkRulesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAssetFamilyCode200ResponseProductLinkRulesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetFamilyCode200ResponseProductLinkRulesInner`
        """
        model = openapi_client.models.get_asset_family_code200_response_product_link_rules_inner.GetAssetFamilyCode200ResponseProductLinkRulesInner()  # noqa: E501
        if include_optional :
            return GetAssetFamilyCode200ResponseProductLinkRulesInner(
                product_selections = [
                    openapi_client.models.get_asset_family__code__200_response_product_link_rules_inner_product_selections_inner.get_asset_family__code__200_response_product_link_rules_inner_product_selections_inner(
                        field = '', 
                        operator = '', 
                        value = '', 
                        locale = '', 
                        channel = '', )
                    ], 
                assign_assets_to = [
                    openapi_client.models.get_asset_family__code__200_response_product_link_rules_inner_assign_assets_to_inner.get_asset_family__code__200_response_product_link_rules_inner_assign_assets_to_inner(
                        attribute = '', 
                        locale = '', 
                        channel = '', 
                        mode = '', )
                    ]
            )
        else :
            return GetAssetFamilyCode200ResponseProductLinkRulesInner(
        )
        """

    def testGetAssetFamilyCode200ResponseProductLinkRulesInner(self):
        """Test GetAssetFamilyCode200ResponseProductLinkRulesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
