# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.attribute_list_all_of_table_configuration import AttributeListAllOfTableConfiguration  # noqa: E501
from openapi_client.rest import ApiException

class TestAttributeListAllOfTableConfiguration(unittest.TestCase):
    """AttributeListAllOfTableConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AttributeListAllOfTableConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributeListAllOfTableConfiguration`
        """
        model = openapi_client.models.attribute_list_all_of_table_configuration.AttributeListAllOfTableConfiguration()  # noqa: E501
        if include_optional :
            return AttributeListAllOfTableConfiguration(
                code = '', 
                data_type = 'select', 
                validations = openapi_client.models.attribute_list_all_of_validations.AttributeList_allOf_validations(
                    min = 1.337, 
                    max = 1.337, 
                    decimals_allowed = True, 
                    max_length = 1.337, ), 
                labels = openapi_client.models.attribute_list_all_of_labels_1.AttributeList_allOf_labels_1(
                    locale_code = '', ), 
                is_required_for_completeness = True
            )
        else :
            return AttributeListAllOfTableConfiguration(
                code = '',
                data_type = 'select',
        )
        """

    def testAttributeListAllOfTableConfiguration(self):
        """Test AttributeListAllOfTableConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
