# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.catalog_products_api import CatalogProductsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCatalogProductsApi(unittest.TestCase):
    """CatalogProductsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.catalog_products_api.CatalogProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_app_catalog_product_uuids(self):
        """Test case for get_app_catalog_product_uuids

        Get the list of product uuids  # noqa: E501
        """
        pass

    def test_get_app_catalog_products(self):
        """Test case for get_app_catalog_products

        Get the list of products related to a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalog_products_uuid(self):
        """Test case for get_app_catalog_products_uuid

        Get a product related to a catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
