# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_products_request_values import PostProductsRequestValues  # noqa: E501
from openapi_client.rest import ApiException

class TestPostProductsRequestValues(unittest.TestCase):
    """PostProductsRequestValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostProductsRequestValues
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostProductsRequestValues`
        """
        model = openapi_client.models.post_products_request_values.PostProductsRequestValues()  # noqa: E501
        if include_optional :
            return PostProductsRequestValues(
                attribute_code = [
                    openapi_client.models.post_products_request_values_attribute_code_inner.post_products_request_values_attributeCode_inner(
                        scope = '', 
                        locale = '', 
                        data = openapi_client.models.data.data(), 
                        linked_data = openapi_client.models.post_products_request_values_attribute_code_inner_linked_data.post_products_request_values_attributeCode_inner_linked_data(
                            attribute = '', 
                            code = '', 
                            labels = openapi_client.models.labels.labels(), ), )
                    ]
            )
        else :
            return PostProductsRequestValues(
        )
        """

    def testPostProductsRequestValues(self):
        """Test PostProductsRequestValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
