# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.products1_embedded import Products1Embedded  # noqa: E501
from openapi_client.rest import ApiException

class TestProducts1Embedded(unittest.TestCase):
    """Products1Embedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Products1Embedded
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Products1Embedded`
        """
        model = openapi_client.models.products1_embedded.Products1Embedded()  # noqa: E501
        if include_optional :
            return Products1Embedded(
                items = [
                    openapi_client.models.products_1__embedded_items_inner.Products_1__embedded_items_inner()
                    ]
            )
        else :
            return Products1Embedded(
        )
        """

    def testProducts1Embedded(self):
        """Test Products1Embedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
