# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.get_variation_files_channel_code_locale_code200_response import GetVariationFilesChannelCodeLocaleCode200Response  # noqa: E501
from openapi_client.rest import ApiException

class TestGetVariationFilesChannelCodeLocaleCode200Response(unittest.TestCase):
    """GetVariationFilesChannelCodeLocaleCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetVariationFilesChannelCodeLocaleCode200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetVariationFilesChannelCodeLocaleCode200Response`
        """
        model = openapi_client.models.get_variation_files_channel_code_locale_code200_response.GetVariationFilesChannelCodeLocaleCode200Response()  # noqa: E501
        if include_optional :
            return GetVariationFilesChannelCodeLocaleCode200Response(
                code = '', 
                locale = '', 
                scope = '', 
                link = openapi_client.models.get_variation_files__channel_code__locale_code_200_response__link.get_variation_files__channel_code__locale_code_200_response__link(
                    download = openapi_client.models.pam_assets__embedded_items_inner_all_of_variation_files_inner__link_download.PAM_Assets__embedded_items_inner_allOf_variation_files_inner__link_download(
                        href = '', ), )
            )
        else :
            return GetVariationFilesChannelCodeLocaleCode200Response(
        )
        """

    def testGetVariationFilesChannelCodeLocaleCode200Response(self):
        """Test GetVariationFilesChannelCodeLocaleCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
