# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.attribute_api import AttributeApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAttributeApi(unittest.TestCase):
    """AttributeApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.attribute_api.AttributeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attributes(self):
        """Test case for get_attributes

        Get list of attributes  # noqa: E501
        """
        pass

    def test_get_attributes_code(self):
        """Test case for get_attributes_code

        Get an attribute  # noqa: E501
        """
        pass

    def test_patch_attributes(self):
        """Test case for patch_attributes

        Update/create several attributes  # noqa: E501
        """
        pass

    def test_patch_attributes_code(self):
        """Test case for patch_attributes_code

        Update/create an attribute  # noqa: E501
        """
        pass

    def test_post_attributes(self):
        """Test case for post_attributes

        Create a new attribute  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
