# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.product_list_all_of1 import ProductListAllOf1  # noqa: E501
from openapi_client.rest import ApiException

class TestProductListAllOf1(unittest.TestCase):
    """ProductListAllOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProductListAllOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductListAllOf1`
        """
        model = openapi_client.models.product_list_all_of1.ProductListAllOf1()  # noqa: E501
        if include_optional :
            return ProductListAllOf1(
                uuid = '', 
                identifier = '', 
                enabled = True, 
                family = 'null only in the case of a non variant product', 
                categories = [
                    ''
                    ], 
                groups = [
                    ''
                    ], 
                parent = '', 
                values = {
                    'key' : [
                        None
                        ]
                    }, 
                associations = openapi_client.models.product_list_all_of_1_associations.ProductList_allOf_1_associations(
                    association_type_code = openapi_client.models.product_list_all_of_1_associations_association_type_code.ProductList_allOf_1_associations_associationTypeCode(
                        groups = [
                            ''
                            ], 
                        products = [
                            ''
                            ], 
                        product_models = [
                            ''
                            ], ), ), 
                quantified_associations = openapi_client.models.product_list_all_of_1_quantified_associations.ProductList_allOf_1_quantified_associations(
                    quantified_association_type_code = openapi_client.models.product_list_all_of_1_quantified_associations_quantified_association_type_code.ProductList_allOf_1_quantified_associations_quantifiedAssociationTypeCode(
                        products = [
                            openapi_client.models.product_list_all_of_1_quantified_associations_quantified_association_type_code_products.ProductList_allOf_1_quantified_associations_quantifiedAssociationTypeCode_products(
                                identifier = '', 
                                quantity = 56, )
                            ], 
                        product_models = [
                            openapi_client.models.product_list_all_of_1_quantified_associations_quantified_association_type_code_product_models.ProductList_allOf_1_quantified_associations_quantifiedAssociationTypeCode_product_models(
                                code = '', 
                                quantity = 56, )
                            ], ), ), 
                created = '', 
                updated = '', 
                metadata = openapi_client.models.product_list_all_of_1_metadata.ProductList_allOf_1_metadata(
                    workflow_status = 'read_only', ), 
                quality_scores = None, 
                completenesses = [
                    openapi_client.models.product_list_all_of_1_completenesses.ProductList_allOf_1_completenesses(
                        scope = '', 
                        locale = '', 
                        data = 56, )
                    ]
            )
        else :
            return ProductListAllOf1(
                identifier = '',
        )
        """

    def testProductListAllOf1(self):
        """Test ProductListAllOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
