# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.reference_entity_record_api import ReferenceEntityRecordApi  # noqa: E501
from openapi_client.rest import ApiException


class TestReferenceEntityRecordApi(unittest.TestCase):
    """ReferenceEntityRecordApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.reference_entity_record_api.ReferenceEntityRecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reference_entity_records(self):
        """Test case for get_reference_entity_records

        Get the list of the records of a reference entity  # noqa: E501
        """
        pass

    def test_get_reference_entity_records_code(self):
        """Test case for get_reference_entity_records_code

        Get a record of a given reference entity  # noqa: E501
        """
        pass

    def test_patch_reference_entity_records(self):
        """Test case for patch_reference_entity_records

        Update/create several reference entity records  # noqa: E501
        """
        pass

    def test_patch_reference_entity_records_code(self):
        """Test case for patch_reference_entity_records_code

        Update/create a record of a given reference entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
