# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.asset_family_list import AssetFamilyList  # noqa: E501
from openapi_client.rest import ApiException

class TestAssetFamilyList(unittest.TestCase):
    """AssetFamilyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AssetFamilyList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetFamilyList`
        """
        model = openapi_client.models.asset_family_list.AssetFamilyList()  # noqa: E501
        if include_optional :
            return AssetFamilyList(
                links = openapi_client.models.product_list_all_of__links.ProductList_allOf__links(
                    self = openapi_client.models.product_list_all_of__links_self.ProductList_allOf__links_self(
                        href = '', ), ), 
                code = '', 
                labels = openapi_client.models.asset_family_list_all_of_labels.AssetFamilyList_allOf_labels(
                    locale_code = '', ), 
                attribute_as_main_media = 'First media file or media link attribute that was created', 
                naming_convention = openapi_client.models.asset_family_list_all_of_naming_convention.AssetFamilyList_allOf_naming_convention(
                    source = openapi_client.models.source.source(), 
                    pattern = '', 
                    abort_asset_creation_on_error = True, ), 
                product_link_rules = [
                    openapi_client.models.asset_family_list_all_of_product_link_rules.AssetFamilyList_allOf_product_link_rules(
                        product_selections = [
                            openapi_client.models.asset_family_list_all_of_product_selections.AssetFamilyList_allOf_product_selections(
                                field = '', 
                                operator = '', 
                                value = '', 
                                locale = '', 
                                channel = '', )
                            ], 
                        assign_assets_to = [
                            openapi_client.models.asset_family_list_all_of_assign_assets_to.AssetFamilyList_allOf_assign_assets_to(
                                attribute = '', 
                                locale = '', 
                                channel = '', 
                                mode = '', )
                            ], )
                    ], 
                transformations = [
                    openapi_client.models.asset_family_list_all_of_transformations.AssetFamilyList_allOf_transformations(
                        label = '', 
                        filename_suffix = '', 
                        filename_prefix = '', 
                        source = openapi_client.models.asset_family_list_all_of_source.AssetFamilyList_allOf_source(
                            attribute = '', 
                            channel = '', 
                            locale = '', ), 
                        target = openapi_client.models.asset_family_list_all_of_target.AssetFamilyList_allOf_target(
                            attribute = '', 
                            channel = '', 
                            locale = '', ), 
                        operations = openapi_client.models.asset_family_list_all_of_operations.AssetFamilyList_allOf_operations(
                            type = '', 
                            parameters = openapi_client.models.asset_family_list_all_of_operations_parameters.AssetFamilyList_allOf_operations_parameters(
                                colorspace = '', 
                                width = 56, 
                                height = 56, 
                                ratio = 56, 
                                resolution_unit = '', 
                                resolution_x = 56, 
                                resolution_y = 56, 
                                quality = 56, ), ), )
                    ]
            )
        else :
            return AssetFamilyList(
                code = '',
        )
        """

    def testAssetFamilyList(self):
        """Test AssetFamilyList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
