# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.media_files_embedded import MediaFilesEmbedded  # noqa: E501
from openapi_client.rest import ApiException

class TestMediaFilesEmbedded(unittest.TestCase):
    """MediaFilesEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MediaFilesEmbedded
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaFilesEmbedded`
        """
        model = openapi_client.models.media_files_embedded.MediaFilesEmbedded()  # noqa: E501
        if include_optional :
            return MediaFilesEmbedded(
                items = [
                    openapi_client.models.media_files__embedded_items_inner.MediaFiles__embedded_items_inner()
                    ]
            )
        else :
            return MediaFilesEmbedded(
        )
        """

    def testMediaFilesEmbedded(self):
        """Test MediaFilesEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
