# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.asset import Asset  # noqa: E501
from openapi_client.rest import ApiException

class TestAsset(unittest.TestCase):
    """Asset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Asset
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Asset`
        """
        model = openapi_client.models.asset.Asset()  # noqa: E501
        if include_optional :
            return Asset(
                embedded = openapi_client.models.asset__embedded.Asset__embedded(
                    _items = [
                        openapi_client.models.asset__embedded__items_inner.Asset__embedded__items_inner()
                        ], ), 
                links = openapi_client.models.reference_entities__links.Reference_Entities__links(
                    self = openapi_client.models.products__links_self.Products__links_self(
                        href = '', ), 
                    first = openapi_client.models.products__links_first.Products__links_first(
                        href = '', ), 
                    next = openapi_client.models.products__links_next.Products__links_next(
                        href = '', ), )
            )
        else :
            return Asset(
        )
        """

    def testAsset(self):
        """Test Asset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
