# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.media_files_embedded_items_inner_all_of_links import MediaFilesEmbeddedItemsInnerAllOfLinks

class MediaFilesEmbeddedItemsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    links: Optional[MediaFilesEmbeddedItemsInnerAllOfLinks] = Field(None, alias="_links")
    code: Optional[StrictStr] = Field(None, description="Media file code")
    original_filename: Optional[StrictStr] = Field(None, description="Original filename of the media file")
    mime_type: Optional[StrictStr] = Field(None, description="Mime type of the media file")
    size: Optional[StrictInt] = Field(None, description="Size of the media file")
    extension: Optional[StrictStr] = Field(None, description="Extension of the media file")
    __properties = ["_links", "code", "original_filename", "mime_type", "size", "extension"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MediaFilesEmbeddedItemsInner:
        """Create an instance of MediaFilesEmbeddedItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MediaFilesEmbeddedItemsInner:
        """Create an instance of MediaFilesEmbeddedItemsInner from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MediaFilesEmbeddedItemsInner.parse_obj(obj)

        _obj = MediaFilesEmbeddedItemsInner.parse_obj({
            "links": MediaFilesEmbeddedItemsInnerAllOfLinks.from_dict(obj.get("_links")) if obj.get("_links") is not None else None,
            "code": obj.get("code"),
            "original_filename": obj.get("original_filename"),
            "mime_type": obj.get("mime_type"),
            "size": obj.get("size"),
            "extension": obj.get("extension")
        })
        return _obj

