# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.reference_entities_embedded_items_inner_all_of1_labels import ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels

class ReferenceEntitiesEmbeddedItemsInnerAllOf1(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    code: StrictStr = Field(..., description="Reference entity code")
    labels: Optional[ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels] = None
    image: Optional[StrictStr] = Field('null', description="Code of the reference entity image")
    __properties = ["code", "labels", "image"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReferenceEntitiesEmbeddedItemsInnerAllOf1:
        """Create an instance of ReferenceEntitiesEmbeddedItemsInnerAllOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of labels
        if self.labels:
            _dict['labels'] = self.labels.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReferenceEntitiesEmbeddedItemsInnerAllOf1:
        """Create an instance of ReferenceEntitiesEmbeddedItemsInnerAllOf1 from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ReferenceEntitiesEmbeddedItemsInnerAllOf1.parse_obj(obj)

        _obj = ReferenceEntitiesEmbeddedItemsInnerAllOf1.parse_obj({
            "code": obj.get("code"),
            "labels": ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels.from_dict(obj.get("labels")) if obj.get("labels") is not None else None,
            "image": obj.get("image") if obj.get("image") is not None else 'null'
        })
        return _obj

