# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from openapi_client.models.products_embedded_items_inner_all_of_links_self import ProductsEmbeddedItemsInnerAllOfLinksSelf
from openapi_client.models.reference_entities_embedded_items_inner_all_of_links_image_download import ReferenceEntitiesEmbeddedItemsInnerAllOfLinksImageDownload

class ReferenceEntitiesEmbeddedItemsInnerAllOfLinks(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    var_self: Optional[ProductsEmbeddedItemsInnerAllOfLinksSelf] = Field(None, alias="self")
    image_download: Optional[ReferenceEntitiesEmbeddedItemsInnerAllOfLinksImageDownload] = None
    __properties = ["self", "image_download"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReferenceEntitiesEmbeddedItemsInnerAllOfLinks:
        """Create an instance of ReferenceEntitiesEmbeddedItemsInnerAllOfLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of var_self
        if self.var_self:
            _dict['self'] = self.var_self.to_dict()
        # override the default output from pydantic by calling `to_dict()` of image_download
        if self.image_download:
            _dict['image_download'] = self.image_download.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReferenceEntitiesEmbeddedItemsInnerAllOfLinks:
        """Create an instance of ReferenceEntitiesEmbeddedItemsInnerAllOfLinks from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ReferenceEntitiesEmbeddedItemsInnerAllOfLinks.parse_obj(obj)

        _obj = ReferenceEntitiesEmbeddedItemsInnerAllOfLinks.parse_obj({
            "var_self": ProductsEmbeddedItemsInnerAllOfLinksSelf.from_dict(obj.get("self")) if obj.get("self") is not None else None,
            "image_download": ReferenceEntitiesEmbeddedItemsInnerAllOfLinksImageDownload.from_dict(obj.get("image_download")) if obj.get("image_download") is not None else None
        })
        return _obj

