# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr, conint

from typing import Optional

from openapi_client.models.attributes import Attributes
from openapi_client.models.attributes_embedded_items_inner_all_of import AttributesEmbeddedItemsInnerAllOf
from openapi_client.models.patch_attributes_request import PatchAttributesRequest
from openapi_client.models.patch_products200_response import PatchProducts200Response

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class AttributeApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_attributes(self, search : Annotated[Optional[StrictStr], Field(description="Filter attributes, for more details see the <a href=\"/documentation/filter.html#filter-attributes\">Filters</a> section.")] = None, page : Annotated[Optional[StrictInt], Field(description="Number of the page to retrieve when using the `page` pagination method type. <strong>Should never be set manually</strong>, see <a href=\"/documentation/pagination.html#pagination\">Pagination</a> section")] = None, limit : Annotated[Optional[conint(strict=True, le=100, ge=1)], Field(description="Number of results by page, see <a href=\"/documentation/pagination.html\">Pagination</a> section")] = None, with_count : Annotated[Optional[StrictBool], Field(description="Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way")] = None, with_table_select_options : Annotated[Optional[StrictBool], Field(description="Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)")] = None, **kwargs) -> Attributes:  # noqa: E501
        """Get list of attributes  # noqa: E501

        This endpoint allows you to get a list of attributes. Attributes are paginated and sorted by code.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_attributes(search, page, limit, with_count, with_table_select_options, async_req=True)
        >>> result = thread.get()

        :param search: Filter attributes, for more details see the <a href=\"/documentation/filter.html#filter-attributes\">Filters</a> section.
        :type search: str
        :param page: Number of the page to retrieve when using the `page` pagination method type. <strong>Should never be set manually</strong>, see <a href=\"/documentation/pagination.html#pagination\">Pagination</a> section
        :type page: int
        :param limit: Number of results by page, see <a href=\"/documentation/pagination.html\">Pagination</a> section
        :type limit: int
        :param with_count: Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way
        :type with_count: bool
        :param with_table_select_options: Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
        :type with_table_select_options: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Attributes
        """
        kwargs['_return_http_data_only'] = True
        return self.get_attributes_with_http_info(search, page, limit, with_count, with_table_select_options, **kwargs)  # noqa: E501

    @validate_arguments
    def get_attributes_with_http_info(self, search : Annotated[Optional[StrictStr], Field(description="Filter attributes, for more details see the <a href=\"/documentation/filter.html#filter-attributes\">Filters</a> section.")] = None, page : Annotated[Optional[StrictInt], Field(description="Number of the page to retrieve when using the `page` pagination method type. <strong>Should never be set manually</strong>, see <a href=\"/documentation/pagination.html#pagination\">Pagination</a> section")] = None, limit : Annotated[Optional[conint(strict=True, le=100, ge=1)], Field(description="Number of results by page, see <a href=\"/documentation/pagination.html\">Pagination</a> section")] = None, with_count : Annotated[Optional[StrictBool], Field(description="Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way")] = None, with_table_select_options : Annotated[Optional[StrictBool], Field(description="Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)")] = None, **kwargs):  # noqa: E501
        """Get list of attributes  # noqa: E501

        This endpoint allows you to get a list of attributes. Attributes are paginated and sorted by code.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_attributes_with_http_info(search, page, limit, with_count, with_table_select_options, async_req=True)
        >>> result = thread.get()

        :param search: Filter attributes, for more details see the <a href=\"/documentation/filter.html#filter-attributes\">Filters</a> section.
        :type search: str
        :param page: Number of the page to retrieve when using the `page` pagination method type. <strong>Should never be set manually</strong>, see <a href=\"/documentation/pagination.html#pagination\">Pagination</a> section
        :type page: int
        :param limit: Number of results by page, see <a href=\"/documentation/pagination.html\">Pagination</a> section
        :type limit: int
        :param with_count: Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way
        :type with_count: bool
        :param with_table_select_options: Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
        :type with_table_select_options: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Attributes, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'search',
            'page',
            'limit',
            'with_count',
            'with_table_select_options'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_attributes" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))
        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))
        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))
        if _params.get('with_count') is not None:  # noqa: E501
            _query_params.append(('with_count', _params['with_count']))
        if _params.get('with_table_select_options') is not None:  # noqa: E501
            _query_params.append(('with_table_select_options', _params['with_table_select_options']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))

        # process the form parameters
        _form_params = []
        _files = {}

        # process the body parameter
        _body_params = None

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', '_links', 'current_page', '_embedded', 'code', 'message'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "Attributes",
            '401': "GetProducts401Response",
            '403': "GetProducts401Response",
            '406': "GetProducts401Response",
        }

        return self.api_client.call_api(
            '/api/rest/v1/attributes', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_attributes_code(self, code : Annotated[StrictStr, Field(..., description="Code of the resource")], with_table_select_options : Annotated[Optional[StrictBool], Field(description="Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)")] = None, **kwargs) -> AttributesEmbeddedItemsInnerAllOf:  # noqa: E501
        """Get an attribute  # noqa: E501

        This endpoint allows you to get the information about a given attribute.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_attributes_code(code, with_table_select_options, async_req=True)
        >>> result = thread.get()

        :param code: Code of the resource (required)
        :type code: str
        :param with_table_select_options: Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
        :type with_table_select_options: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: AttributesEmbeddedItemsInnerAllOf
        """
        kwargs['_return_http_data_only'] = True
        return self.get_attributes_code_with_http_info(code, with_table_select_options, **kwargs)  # noqa: E501

    @validate_arguments
    def get_attributes_code_with_http_info(self, code : Annotated[StrictStr, Field(..., description="Code of the resource")], with_table_select_options : Annotated[Optional[StrictBool], Field(description="Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)")] = None, **kwargs):  # noqa: E501
        """Get an attribute  # noqa: E501

        This endpoint allows you to get the information about a given attribute.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_attributes_code_with_http_info(code, with_table_select_options, async_req=True)
        >>> result = thread.get()

        :param code: Code of the resource (required)
        :type code: str
        :param with_table_select_options: Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
        :type with_table_select_options: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(AttributesEmbeddedItemsInnerAllOf, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'code',
            'with_table_select_options'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_attributes_code" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['code']:
            _path_params['code'] = _params['code']

        # process the query parameters
        _query_params = []
        if _params.get('with_table_select_options') is not None:  # noqa: E501
            _query_params.append(('with_table_select_options', _params['with_table_select_options']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))

        # process the form parameters
        _form_params = []
        _files = {}

        # process the body parameter
        _body_params = None

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'code', 'message'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "AttributesEmbeddedItemsInnerAllOf",
            '401': "GetProducts401Response",
            '403': "GetProducts401Response",
            '404': "GetProducts401Response",
            '406': "GetProducts401Response",
        }

        return self.api_client.call_api(
            '/api/rest/v1/attributes/{code}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def patch_attributes(self, body : Optional[PatchAttributesRequest] = None, **kwargs) -> PatchProducts200Response:  # noqa: E501
        """Update/create several attributes  # noqa: E501

        This endpoint allows you to update and/or create several attributes at once.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.patch_attributes(body, async_req=True)
        >>> result = thread.get()

        :param body:
        :type body: PatchAttributesRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PatchProducts200Response
        """
        kwargs['_return_http_data_only'] = True
        return self.patch_attributes_with_http_info(body, **kwargs)  # noqa: E501

    @validate_arguments
    def patch_attributes_with_http_info(self, body : Optional[PatchAttributesRequest] = None, **kwargs):  # noqa: E501
        """Update/create several attributes  # noqa: E501

        This endpoint allows you to update and/or create several attributes at once.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.patch_attributes_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param body:
        :type body: PatchAttributesRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PatchProducts200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'body'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_attributes" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))

        # process the form parameters
        _form_params = []
        _files = {}

        # process the body parameter
        _body_params = None
        if _params['body']:
            _body_params = _params['body']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'x-example-1', 'x-example-2', 'x-example-3', 'code', 'message'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "PatchProducts200Response",
            '401': "GetProducts401Response",
            '403': "GetProducts401Response",
            '413': "GetProducts401Response",
            '415': "GetProducts401Response",
        }

        return self.api_client.call_api(
            '/api/rest/v1/attributes', 'PATCH',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def patch_attributes_code(self, code : Annotated[StrictStr, Field(..., description="Code of the resource")], body : AttributesEmbeddedItemsInnerAllOf, **kwargs) -> None:  # noqa: E501
        """Update/create an attribute  # noqa: E501

        This endpoint allows you to update a given attribute. Know more about <a href=\"/documentation/update.html#update-behavior\">Update behavior</a>. Note that if no attribute exists for the given code, it creates it.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.patch_attributes_code(code, body, async_req=True)
        >>> result = thread.get()

        :param code: Code of the resource (required)
        :type code: str
        :param body: (required)
        :type body: AttributesEmbeddedItemsInnerAllOf
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.patch_attributes_code_with_http_info(code, body, **kwargs)  # noqa: E501

    @validate_arguments
    def patch_attributes_code_with_http_info(self, code : Annotated[StrictStr, Field(..., description="Code of the resource")], body : AttributesEmbeddedItemsInnerAllOf, **kwargs):  # noqa: E501
        """Update/create an attribute  # noqa: E501

        This endpoint allows you to update a given attribute. Know more about <a href=\"/documentation/update.html#update-behavior\">Update behavior</a>. Note that if no attribute exists for the given code, it creates it.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.patch_attributes_code_with_http_info(code, body, async_req=True)
        >>> result = thread.get()

        :param code: Code of the resource (required)
        :type code: str
        :param body: (required)
        :type body: AttributesEmbeddedItemsInnerAllOf
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'code',
            'body'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_attributes_code" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['code']:
            _path_params['code'] = _params['code']

        # process the query parameters
        _query_params = []

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))

        # process the form parameters
        _form_params = []
        _files = {}

        # process the body parameter
        _body_params = None
        if _params['body']:
            _body_params = _params['body']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'code', 'message', '_links'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/api/rest/v1/attributes/{code}', 'PATCH',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def post_attributes(self, body : Optional[AttributesEmbeddedItemsInnerAllOf] = None, **kwargs) -> None:  # noqa: E501
        """Create a new attribute  # noqa: E501

        This endpoint allows you to create a new attribute.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.post_attributes(body, async_req=True)
        >>> result = thread.get()

        :param body:
        :type body: AttributesEmbeddedItemsInnerAllOf
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.post_attributes_with_http_info(body, **kwargs)  # noqa: E501

    @validate_arguments
    def post_attributes_with_http_info(self, body : Optional[AttributesEmbeddedItemsInnerAllOf] = None, **kwargs):  # noqa: E501
        """Create a new attribute  # noqa: E501

        This endpoint allows you to create a new attribute.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.post_attributes_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param body:
        :type body: AttributesEmbeddedItemsInnerAllOf
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'body'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_attributes" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))

        # process the form parameters
        _form_params = []
        _files = {}

        # process the body parameter
        _body_params = None
        if _params['body']:
            _body_params = _params['body']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'code', 'message', '_links'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/api/rest/v1/attributes', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
